import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import soybeans from './/../images/soybeans.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.hero}>
          <nav className={styles.nav}>
            <ul>
              <li><Link href="/">home</Link></li>
              <li><Link href="/blog">blog</Link></li>
              <li><Link href="/cart">cart</Link></li>
              <li><Link href="/contact">contact us</Link></li>
              <li><Link href="/users">users</Link></li>
            </ul>
          </nav>
      
          <h1>abuot page</h1>
        </section>
        <section>
      <div className={styles.imgdiv}>
        <Image
        className={styles.img}
        src={soybeans}
        alt="/"
        />
        <Image
        className={styles.img}
        src={soybeans}
        alt="/"
        />
        <Image
        className={styles.img}
        src={soybeans}
        alt="/"
        />
        <Image
        className={styles.img}
        src={soybeans}
        alt="/"
        />
      </div>
      </section>
      
      </main>
    </>
  )
}
